name: pylabfea
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pytest
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - nb_conda_kernels
  - ipympl

