name: PyPI Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Clean old builds
        run: rm -rf dist build *.egg-info

      - name: Build sdist/wheel
        run: python -m build
        
      - name: Check distribution metadata
        run: python -m pip install twine && twine check dist/*
  
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: dist
          verbose: true

