name: PyPI Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: python -m pip install --upgrade build twine

      - name: Clean old builds
        run: rm -rf dist build *.egg-info

      - name: Build sdist/wheel
        run: python -m build
        
      - name: Check distribution metadata
        run: twine check dist/*
  
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

