name: pylabfea testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: setup conda
      run: |
        conda --version
        which python
        conda config --set always_yes yes --set changeps1 no
        conda install -c conda-forge numpy matplotlib scipy scikit-learn pytest
        conda update -q conda
        pip install -e .

    - name: run tests
      run: |
        pytest tests/
 